;// __FILE_CONTENT_FOR__:4a930e2397c76056.js
(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[86799],{

/***/ 592914:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);self._456c437108d2d2713799e19380be528d = self._456c437108d2d2713799e19380be528d || {};(function(__c) {var V=__c.V;var S=__c.S;var G=__c.G;var DUr;__c.zUr=G(()=>({type:__c.A("A?",1,"REQUEST"),editor:S(1),z$a:__c.Ua(5,__c.Sjc),W$e:V(6),message:V(3),Jhb:__c.zp(7),page:__c.yp(4)}));__c.AUr=G(()=>({type:__c.A("A?",2,"APPROVE"),A0:S(1),message:V(2)}));__c.BUr=G(()=>({type:__c.A("A?",3,"REJECT"),A0:S(1),message:V(2)}));__c.CUr=G(()=>({type:__c.A("A?",4,"DISMISS"),editor:S(1),fej:__c.Ua(31,__c.Hjc)}));DUr=__c.ab(()=>({type:[1,__c.zUr,2,__c.AUr,3,__c.BUr,4,__c.CUr]}),()=>({}));
__c.EUr=G(()=>({document:S(1),extension:V(5),pr:__c.vp(2),brand:S(3),mode:__c.E(4,DUr)}));__c.BOa.prototype.PVd=__c.ia(150,async function(a){const b=__c.qh(__c.nh([__c.J$c,"document"])),[c,{D0p:d}]=await Promise.all([this.Da.post(b,__c.EUr.serialize(a.body),{Qa:"updatedocumentreviewapi"}),__webpack_require__.me(736797).then(()=>({D0p:__c.okc}))]);return d.deserialize(c)});__c.FUr=G(()=>({body:__c.E("body",1,__c.EUr)}));
}).call(self, self._456c437108d2d2713799e19380be528d);}

}])
;// __FILE_CONTENT_FOR__:6a864be9ddd5733e.js
(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[90628],{

/***/ 321092:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(154652);self._456c437108d2d2713799e19380be528d = self._456c437108d2d2713799e19380be528d || {};(function(__c) {__c.V1r=()=>({limit:__c.vp(11,20),continuation:__c.V(12)});__c.W1r=__c.G(()=>({...__c.V1r(),type:__c.A("A?",1,"BY_RESOURCE"),pa:__c.S(31),resource:__c.E(32,__c.bJ),Sf:__c.V(33)}));
}).call(self, self._456c437108d2d2713799e19380be528d);}

}])
;// __FILE_CONTENT_FOR__:204532102349e2a1.js
(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[32840],{

/***/ 601201:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(764820);__web_req__(558082);__web_req__(533943);__web_req__(309060);__web_req__(321092);__web_req__(592914);__web_req__(157150);__web_req__(493116);self._456c437108d2d2713799e19380be528d = self._456c437108d2d2713799e19380be528d || {};(function(__c) {var M=__c.M;var R=__c.R;var Tfs,Ufs,Vfs,Wfs,fgs,ggs,dgs,hgs,igs,jgs,kgs,lgs,ogs,mgs,ngs,rgs,wgs,aT,pgs;__c.Sfs=function(){const a=new Ofs,b=new Pfs,c=()=>b.IUd(a),d=(e,f)=>b.lmc(a,e,f);return Qfs(({A0:e,feedback:f})=>aT(Rfs,{A0:e,feedback:f,GI:a.GI,rQb:a.rQb,IUd:c,lmc:d}))};Tfs=async function(a,b){try{const {L3i:c}=await a.Qu.SPg(new __c.W1r({pa:a.pa,resource:{id:b,type:1},Sf:a.ea.extension}));return c.length?c[0].fta:void 0}catch(c){a.errorService.ra(Error("Failed to get solo work assigner",{cause:c}))}};
Ufs=async function(a,b){try{const {ff:d}=await a.Jf.VQc({item:b,pa:a.pa,userId:a.userId});if(d.length===1){var {L3i:c}=await a.Qu.SPg(new __c.W1r({pa:a.pa,resource:{id:d[0].id,type:2}}));return c.length?c[0].fta:void 0}}catch(d){a.errorService.ra(Error("Failed to get lesson assigner",{cause:d}))}};Vfs=async function(a,b){const [{user:c},{wu:d}]=await Promise.all([a.Pa.X7a(new __c.N0j({user:b})),a.Dl.gRa(new __c.Xu({my:[b]}))]);return{user:c,email:c.email,Lc:d.get(b)}};
Wfs=async function(a){if(a.Kaa&&await a.Dwf()){var [b,c]=await Promise.all([Tfs(a,a.Kaa),Ufs(a,a.Kaa)]);if(b)try{return Vfs(a,b)}catch(d){a.errorService.ra(Error("Failed to get reviewer while finding a solo work assigner",{cause:d}))}if(c)try{return Vfs(a,c)}catch(d){a.errorService.ra(Error("Failed to get reviewer while finding a lesson assigner",{cause:d}))}}};
fgs=function(a,b){if(b.y$a.status===0){b.y$a.nextPage();b.A6b&&b.y$a.results.push(b.A6b);var c=a.Hy?Xfs(Yfs(()=>b.y$a.page),a.Hy):Zfs(Yfs(()=>b.y$a.page));b.y$a.subscription=__c.DG($fs(ags(0),c),async d=>{bgs(()=>{b.y$a.status=1;b.error=void 0});const e=await a.Tp(),{results:f,continuation:g}=await e.m6b(new __c.jZf({Loe:!0,roles:cgs,continuation:d,csa:b.Wsh,projection:[2,1],limit:20,orderBy:2}));return{continuation:g,results:f}},d=>d.continuation,d=>d.results).subscribe(async d=>{var e=b.y$a.results.map(g=>
[g.user.id,g]);d=d.map(g=>{const h=__c.m(g.rLa);return[h.user.id,{user:h.user,Lc:g.Lc,email:h.email}]});e=new Map([...e,...d]);const f=Array.from(e.values());b.azc&&(d=await dgs(a,b,f))&&(e.has(d.user.id)||f.unshift(d),a.BHl(b,d));bgs(()=>{b.y$a.results=f;b.y$a.status=2;b.azc=!1;b.Wsh==null&&b.y$a.results.length===0&&(b.CWf=!0)})},egs(d=>{b.Wsh==null&&b.y$a.results.length===0&&(b.CWf=!0);b.error=2;b.azc=!1;b.y$a.status=3;a.errorService.ra(Error("Error searching reviewers",{cause:d}))}),egs(()=>{b.y$a.Cc=
!1}))}};ggs=function(a){switch(a.type){case "NEVER_REQUESTED":return"never_requested";case "REQUESTED":return"requested";case "APPROVED":return"feedback_sent";case "REJECTED":return"feedback_sent";case "DISMISSED_AFTER_APPROVED":return"marked_as_complete";case "DISMISSED_AFTER_REJECTED":return"marked_as_complete";case "PREVIOUSLY_REQUESTED":return"requested";default:throw new __c.u(a);}};
dgs=async function(a,b,c){c=b.ztc?.state==="loaded"&&!b.A6b&&c?c.find(({user:d})=>b.ztc?.state==="loaded"&&d.id===b.ztc.A0.user.id):void 0;return b.A6b?b.A6b:c?c:await Wfs(a)};hgs=function(a){return{type:"reviewer",A0:a}};igs=function(a){return{type:"placeholder",index:a,disabled:!0}};
jgs=function(a){switch(a.type){case "reviewer":const b=a.A0;return{Icon:()=>aT(__c.py,{jh:__c.uo(b.Lc?.images??[],"xsmall"),name:b.user.displayName,Gs:b.user.id,size:"xsmall"}),label:b.user.displayName||b.email||b.user.username||" ",value:a};case "placeholder":return{value:a,disabled:!0};case "sentinel":return{value:a};default:throw new __c.u(a);}};kgs=function(a,b){return a===void 0&&b===void 0||a?.type==="reviewer"&&b?.type==="reviewer"&&a.A0.user.id===b.A0.user.id};
lgs=function(a,b){return Array.isArray(b)?b.includes(a.value):kgs(a.value,b)};ogs=function(a){const b=a.option.value;switch(b.type){case "reviewer":return aT(__c.dz,{...a});case "placeholder":return aT(mgs,{index:b.index});case "sentinel":return aT(ngs,{tJa:b.tJa});default:throw new __c.u(b);}};
mgs=function({index:a}){return aT(R,{Fb:"2u",Kc:"1u",children:pgs(__c.tr,{Fa:"start",spacing:"1u",children:[aT(__c.sr,{width:"content",children:aT(__c.eC,{size:"xsmall",index:a})}),aT(__c.sr,{width:"1/2",children:aT(__c.iu,{index:a})})]})})};ngs=function({tJa:a}){var b=qgs(c=>{c&&a()},[a]);({hhb:b}=__c.cjh(b));return aT("div",{ref:b})};
rgs=function({ztc:a,feedback:b,jng:c}){return a.state==="loading"?aT(__c.iu,{}):b?aT(c,{A0:a.A0,feedback:b}):a.A0.user.displayName?aT(__c.Wk,{tone:"positive",children:aT(__c.P,{children:__c.J("IMuDkA",[a.A0.user.displayName||""])})}):null};
__c.vgs=function({userId:a,pa:b,Kaa:c,ya:d,Dl:e,yt:f,errorService:g,Pa:h,Tp:k,Qu:l,Jf:n,onSubmit:p,onSubmitSuccess:q,C5e:r,ea:t,wCe:v}){const w=new sgs,x=new tgs({userId:a,pa:b,Kaa:c,ya:d,Dl:e,yt:f,errorService:g,Pa:h,Tp:k,Qu:l,Jf:n,onSubmitSuccess:egs((H,K)=>{w.reset();q(H,K)}),C5e:r,ea:t,wCe:v}),y=__c.Sfs(),z=H=>x.BHl(w,H),B=H=>x.setMessage(w,H),C=H=>x.ngt(w,H),D=()=>x.LB(w);return Qfs(({j2:H})=>{const K=qgs(()=>{x.ANn(w,H)},[H]),L=qgs(async()=>{await x.submit(w,H,p)},[H]);return aT(ugs,{ztc:w.ztc,
Tgh:z,aDe:w.y$a.results,CWf:w.CWf,XAr:w.y$a.Cc,y3r:w.y$a.nextPage,gTr:w.y$a.status===1,A6b:w.A6b,message:w.message,hMd:B,onSubmit:L,md:K,Ah:D,Yre:w.Yre,azc:w.azc,error:w.error,feedback:w.Vsh,jng:y,Naf:H.type,WAs:C})})};wgs=__webpack_require__(31968);aT=wgs.jsx;pgs=wgs.jsxs;var xgs=__webpack_require__(845212),ygs=xgs.memo,zgs=xgs.PureComponent,qgs=xgs.useCallback,Ags=xgs.useEffect,Bgs=xgs.useRef;var Cgs=__webpack_require__(186901),bgs=Cgs.h5,Dgs=Cgs.sH,egs=Cgs.XI;var Qfs=__webpack_require__(647370).PA;var Xfs=__webpack_require__(502678).c;var Yfs=__webpack_require__(536618)._y;var Zfs=__webpack_require__(212943).H;var $fs=__webpack_require__(296423).x;var ags=__webpack_require__(322546).of;var Egs=__webpack_require__.p+"images/cc910eb74190437c2adbfe52729bf679.png";__c.Fgs=({NDc:a,oN:b})=>pgs(R,{className:"Ijyqpw",children:[aT(R,{display:"flex",justifyContent:"center",alignItems:"center",children:aT(__c.gv,{src:Egs,alt:"",className:"_75Taog"})}),aT(__c.kd,{size:"3u"}),aT(__c.P,{alignment:"center",children:a?__c.J("+ZhLLQ",[a]):M("YMHkLQ")}),aT(__c.kd,{size:"2u"}),b]});var Rfs=({A0:a,feedback:b,GI:c,rQb:d,IUd:e,lmc:f})=>pgs(R,{background:"neutralLow",padding:"1u",borderRadius:"legacyLarge",children:[pgs(__c.tr,{spacing:"1u",Fa:"center",children:[aT(__c.sr,{width:"content",children:aT(__c.py,{jh:__c.uo(a.Lc?.images??[]),name:a.user.displayName,Gs:a.user.id})}),aT(__c.sr,{children:pgs(__c.Wc,{spacing:"0",children:[aT(__c.zr,{weight:"bold",Pu:!0,children:a.user.displayName||""}),b.date&&aT(__c.hF,{time:new Date(b.date),children:g=>aT(__c.P,{tone:"tertiary",lineClamp:1,
size:"small",Pu:!0,children:g})})]})})]}),aT(Ggs,{message:b.message,GI:c,rQb:d,IUd:e,lmc:f})]}),Ggs=({message:a,GI:b,rQb:c,IUd:d,lmc:e})=>{const f=Bgs(null);Ags(()=>{const g=f.current?.firstElementChild;g&&e(g.clientHeight,g.scrollHeight)},[e]);return pgs(__c.Wc,{spacing:"1u",align:"start",children:[aT(R,{ref:f,children:aT(__c.P,{Pu:!0,lineClamp:b?void 0:3,children:a})}),c&&aT(__c.nj,{variant:"linkButton",size:"tiny",onClick:d,children:b?M("9oYu9A"):M("SeWYfA")})]})};var Ofs=class{static G(a){__c.N(a,{GI:Dgs.ref,rQb:Dgs.ref})}constructor(){this.GI=(Ofs.G(this),!1);this.rQb=!1}},Pfs=class{static G(a){__c.N(a,{IUd:egs,lmc:egs})}IUd(a){a.GI=!a.GI}lmc(a,b,c){c>b&&(a.rQb=!0)}constructor(){Pfs.G(this)}};__c.Hgs={eventType:"classwork_editor_interacted",Ka(a){return __c.rf({action:a.action,step_name:a.MH,design_id:a.designId,teacher_id:a.teacherId,student_id:a.studentId,message_length:a.rKd,previous_review_state:a.uUs,assignment_type:a.MZh})}};var sgs=class{static G(a){__c.N(a,{A6b:Dgs.ref,ztc:Dgs.ref,Vsh:Dgs.ref,message:Dgs.ref,Yre:Dgs.ref,error:Dgs.ref,azc:Dgs.ref})}reset(){this.A6b=void 0;this.message="";this.Yre=!1}constructor(){this.Wsh=(sgs.G(this),void 0);this.y$a=new __c.yv;this.CWf=!1;this.message="";this.azc=this.Yre=!1}},cgs=[4,3,2],tgs=class{static G(a){__c.N(a,{BHl:egs,setMessage:egs,ANn:egs,LB:egs,ELl:egs,SMn:egs,TKo:egs})}async Dwf(){if(!this.Kaa)return!1;try{const {wrc:a}=await this.Qu.Dwf({pa:this.pa,resource:{type:1,id:this.Kaa},
IZh:this.userId});return a?!0:!1}catch(a){this.errorService.ra(Error("Failed to check assignment status",{cause:a}))}}BHl(a,b){(a.A6b=b)&&this.C5e?.(b.user.id)}setMessage(a,b){a.message=b}async ANn(a,b){if(!a.azc)return a.azc=!0,this.ya.track(__c.Hgs,{action:"step_shown",MH:"send_to_teacher",designId:this.ea.id,studentId:this.userId,MZh:this.wCe}),this.TKo(a,b),Promise.all([this.SMn(a,b),fgs(this,a)])}LB(a){a.azc=!1;a.error=void 0;a.CWf=!1;a.A6b=void 0;a.y$a.reset();a.Wsh=void 0}async submit(a,b,
c){const d=__c.m(a.A6b,"Can't submit before a reviewer is selected");try{bgs(()=>{a.Yre=!0;a.error=void 0});await this.ea.sync();await c?.(d.user.id,a.message);const e=await this.yt.PVd(new __c.FUr({body:new __c.EUr({document:this.ea.id,extension:this.ea.extension,pr:this.ea.version,brand:this.pa,mode:new __c.zUr({editor:this.userId,z$a:[new __c.Qjc({Sra:1,user:d.user.id})],message:a.message})})}));e instanceof __c.mkc?(this.ya.track(__c.Hgs,{action:"sent_to_teacher",designId:this.ea.id,teacherId:d.user.id,
studentId:this.userId,rKd:a.message.length,uUs:ggs(b),MZh:this.wCe}),this.onSubmitSuccess(e.eGa,d),bgs(()=>a.Yre=!1)):this.ELl(a)}catch{this.ELl(a)}}ELl(a){a.Yre=!1;a.error=1}async SMn(a,b){switch(b.type){case "REQUESTED":case "APPROVED":case "REJECTED":b=b.A0;break;case "DISMISSED_AFTER_APPROVED":b=b.iMb;break;case "DISMISSED_AFTER_REJECTED":b=b.lTb;break;case "PREVIOUSLY_REQUESTED":case "NEVER_REQUESTED":return;default:return}if(b){a.ztc={state:"loading"};try{const c=await Vfs(this,b);bgs(()=>a.ztc=
{state:"loaded",A0:c})}catch(c){this.errorService.ra(Error("Failed to fetch current reviewer",{cause:c})),bgs(()=>a.ztc=void 0)}}else a.ztc=void 0}TKo(a,b){switch(b.type){case "APPROVED":b.message&&(a.Vsh={date:b.zXb,message:b.message});break;case "REJECTED":b.message&&(a.Vsh={date:b.j_c,message:b.message});break;case "DISMISSED_AFTER_APPROVED":b.message&&(a.Vsh={date:b.zXb,message:b.message});break;case "DISMISSED_AFTER_REJECTED":b.message&&(a.Vsh={date:b.j_c,message:b.message})}}constructor({userId:a,
pa:b,Kaa:c,ya:d,Dl:e,yt:f,errorService:g,Pa:h,Tp:k,Qu:l,Jf:n,Hy:p,ea:q,onSubmitSuccess:r,C5e:t,debounce:v=__c.Db,wCe:w}){this.pa=(tgs.G(this),void 0);this.userId=a;this.pa=b;this.Kaa=c;this.ya=d;this.Dl=e;this.yt=f;this.errorService=g;this.Pa=h;this.Tp=k;this.Qu=l;this.Jf=n;this.Hy=p;this.ea=q;this.onSubmitSuccess=r;this.C5e=t;this.wCe=w;this.ngt=v((x,y)=>{x.Wsh=y;x.y$a.reset();fgs(this,x)},500)}};var Igs=ygs(({aDe:a,A6b:b,Tgh:c,YU:d,azc:e,...f})=>{a=a!=null?a.map(jgs):[];return aT(__c.ez,{...f,YU:d,value:b,YP:kgs,oc:lgs,options:a,onChange:c,placeholder:M("u14C8A"),stretch:!0,item:ogs,Trigger:g=>aT(__c.bz,{...g,disabled:e,children:e?aT(__c.iu,{}):void 0})})}),ugs=class extends zgs{componentDidMount(){this.props.md()}componentWillUnmount(){this.props.Ah()}render(){var a=this.props.aDe;const b=this.props.azc;var c=this.props.gTr,d=this.props.XAr,e=this.props.y3r;const f=this.props.ztc,g=this.props.A6b,
h=this.props.message,k=this.props.Yre,l=this.props.hMd,n=this.props.onSubmit,p=this.props.feedback,q=this.props.jng,r=this.props.WAs;var t=this.props.error;if(this.props.CWf)return aT("div",{className:"pHjfbg",children:aT(__c.Wk,{tone:"critical",children:M("eN8TOw")})});const v=[...(a!=null&&a.length>0?a.map(hgs):[]),...(c?[0,1,2].map(igs):[]),...(d&&!c?[{type:"sentinel",tJa:e,disabled:!0}]:[])];a=f&&aT(rgs,{ztc:f,feedback:p,jng:q});c=pgs("div",{className:"O_k30g",children:[t===2&&aT("div",{className:"pHjfbg",
children:aT(__c.Wk,{tone:"critical",size:"small",children:M("7qmW3A")})}),aT(__c.kA,{label:M("U68vGQ"),control:w=>aT(Igs,{...w,aDe:v,A6b:g?hgs(g):void 0,Tgh:this.Tgh,YU:{mtb:(x,y)=>y,NE:x=>r(x)},azc:b})})]});d=aT("div",{className:"O_k30g",children:aT(__c.kA,{label:M("3g4Rxg"),control:w=>aT(__c.vC,{...w,value:h,maxLength:1500,onChange:l,footer:aT(__c.Ev,{count:h?.length||0,max:1500,margins:"horizontal"}),Rn:5})})});t=t===1&&aT(__c.Wk,{tone:"critical",size:"small",children:M("l69fww")});a:switch(this.props.Naf){case "DISMISSED_AFTER_APPROVED":case "REJECTED":case "DISMISSED_AFTER_REJECTED":e=
M("J9jDSA");break a;default:e=M("9sLU4w")}return pgs("div",{className:"pHjfbg",children:[a,c,d,t,aT(__c.nj,{variant:"primary",className:"OrJJrg",onClick:n,disabled:!g,loading:k,children:e})]})}constructor(...a){super(...a);this.Tgh=b=>{__c.ta(b.type==="reviewer",`Unexpected option type selected: ${b.type}`);this.props.Tgh(b.A0)}}};
}).call(self, self._456c437108d2d2713799e19380be528d);}

}])
;// __FILE_CONTENT_FOR__:8c0de5e7160b8856.js
(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[24701],{

/***/ 310086:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(756500);__web_req__(909567);__web_req__(64460);__web_req__(660244);__web_req__(993375);__web_req__(233947);__web_req__(764820);__web_req__(817677);__web_req__(481431);__web_req__(578363);__web_req__(995621);__web_req__(347675);__web_req__(601201);__web_req__(675040);self._456c437108d2d2713799e19380be528d = self._456c437108d2d2713799e19380be528d || {};(function(__c) {var P=__c.P;var sr=__c.sr;var nj=__c.nj;var Wc=__c.Wc;var N=__c.N;var M=__c.M;var R=__c.R;
var EYy=async function(a,b,c,d){var e=b.length;b=Array.from(b);let f=[];const g=Array(e).fill("NoResponse");let h=0;for(;b.length>0;){if(e=b.shift())e=a.MA.FHf(new __c.cYn({designId:c,jg:d,eg:e.eg,wN:e.wN,limit:1,sortOrder:2,status:1})),f.push(e);if(f.length>=5||b.length===0){e=h;const k=[];(await Promise.allSettled(f)).forEach(l=>{g[h]=l.status==="fulfilled"&&l.value.YS.length>0?l.value.YS[0]:"NoResponse";l.status==="rejected"&&k.push(l.reason);h+=1});if(k.length>0){const l=Array.from(new Set(k)).join(", ");
a.errorService.ra(Error(l),{Ma:"Unable to get submissions for quiz elements"})}h=e+f.length;f=[]}}return g},GYy=function(a,b,c){return FYy.create(b,c,a.map((d,e)=>({Md:d.Iwl.Md,wN:d.Iwl.wN,Elr:d.Iwl.field.label,FYg:d.QYs!=="NoResponse",index:e})))},IYy=function(a,b){return a.map((c,d)=>new HYy(c,b[d]))},JYy=async function(a){const {Jwl:b,ja:c,extension:d}=a.RCk();if(b.length===0)return FYy.empty();a=await EYy(a,b,c,d);return GYy(IYy(b,a),c,d)},KYy=function(a,b){return a.PYs.filter(c=>b===c.Md&&!c.FYg)},
LYy=async function(a,b,c){let d,e,f;do{const {items:g,continuation:h}=await a.WFb(b,f),k=await __c.wYy(a,b,g);f=h;if(k)for(const [l,n]of g.entries()){if(!e&&n.id===c){e=l;continue}const p=k.get(n.id);if(p&&p.status!==1){if(e)return n;d||(d=n)}}}while(f);return d},MYy=async function(a,b,c){let d,e;do{const {items:f,continuation:g}=await a.WFb(b,e);for(const [h,k]of f.entries())if(!d&&k.id===c)d=h;else if(d!==void 0)return k;e=g}while(e)},OYy=function({errorService:a}){if(window.top!==window.self){var {iCb:b,
eX:c}=__c.tao({key:6,serialize:__c.sMs.serialize,deserialize:__c.uMs.deserialize,onError:d=>{a.error(d instanceof Error?d:String(d),{fingerprint:["lessonNextActivityCrossFrameChild"]})}});return{iCb:b,eX:c,events:NYy}}},YYy=function({Ome:a,viewport:b}){const {lDa:c,KIc:d,RH:e}=__c.oz(),f=new PYy(e),g=new QYy(a,b),h={navigate:q=>g.navigate(f,q),nNa:()=>{e.clear();g.nNa(f)},Jp:()=>{e.clear();g.Jp(f)}},k=F1(()=>{g.qfj(f);e.clear()}),l=RYy(()=>G1(SYy,{state:f.state,selectedIndex:f.selectedIndex,navigator:h})),
n=()=>G1(TYy,{navigator:h}),p=RYy(()=>G1(__c.id,{title:__c.J("6yvDFQ",[f.C3f?.sWn||0]),alignment:"start",end:G1(__c.gd,{onClick:k})}));a=F1(()=>{g.gWo(f);e.gna===0&&e.Ku({body:G1(UYy,{qa:l,$Xd:n}),header:G1(p,{})})});return{sLp:VYy(function(){return G1(R,{height:"full",flexDirection:"column",display:"flex",className:"_1YoXsg",padding:"0",children:WYy(R,{className:"vur3tw",borderRadius:"container",children:[G1(d,{}),G1(__c.eu,{}),G1(c,{})]})})}),controller:new XYy(f,g,a)}},$Yy=async function(a){const {kvl:b}=
await a.$$d();if(b!==1)try{await a.zVc.Xbp({Aa:a.r9c,VO:a.KJ,zPd:a.KJ!==a.ja?a.ja:void 0}),a.ya.track(ZYy,{action:"activity_completed",Ad:a.r9c,KJ:a.KJ,designId:a.ja})}catch(c){throw a.errorService.ra(Error("Failed to mark activity as completed",{cause:c})),c;}},bZy=async function(a,b){const c=a.Wgd,d=await aZy(a);d&&(c?c.eX.postMessage({type:"NAVIGATE_ACTIVITY",VO:d.id,rzf:b}):(b=await __c.jMs(a.hvb.lhc,{ivb:a.hvb.ivb,Aa:{id:a.r9c,access:a.N1j},design:{id:d.id,title:d.document?.draft.content.title,
extension:d.document?.uc.extension},bVl:void 0}))?(a.ya.track(__c.SM,{action:"assignment_opened",designId:d.id,etg:{DXb:d.id,cTd:b.cTd,LDl:b.cTd==="resume"?b.design.id:void 0},CLn:a.r9c,source:"editor",location:"next_activity"}),await __c.Lv(a.Qb,{id:b.design.id,extensions:b.design.extensions,Ic:__c.RWr({Tbc:a.r9c,y7h:a.N1j,KJ:d.id,fXa:1})},{target:"_self"})):await __c.Lv(a.Qb,{id:d.id,extensions:new __c.sj({default:d?.document?.uc.extension}),Ic:__c.RWr({Tbc:a.r9c,y7h:a.N1j,KJ:d.id,fXa:2})},{target:"_self"}))},
aZy=async function(a){const {HLj:b,M3g:c}=await a.$$d();if(b||c)try{const d=await MYy(a.Rnh,a.r9c,a.KJ);d||a.mc.Gb({sb:M("Y1YLCQ")});return d}catch(d){throw a.errorService.ra(Error("Next Activity: Failed to find next activity",{cause:d})),d;}else try{return LYy(a.Rnh,a.r9c,a.KJ)}catch(d){throw a.errorService.ra(Error("Next Activity: Failed to find next activity",{cause:d})),d;}},cZy=async function(a,b,c){a.e7.Dsc.QGc(a.e7.rQa,b);a.Wgd&&a.Wgd.eX.postMessage((await a.e7.$$d()).M3g?{type:"FINISH_LESSON",
rzf:2}:{type:"UPDATE_CURRENT_ACTIVITY_PROGRESS",nrm:2});a.zEc.GAc(a.AEc,{MH:"activity_sent",I:{l2:c.user.id,NDc:c.user.displayName}})},dZy=function(a,b,c){a.ya.track(ZYy,{action:"flyout_closed",Ad:a.e7.CEc,KJ:a.e7.KJ,designId:a.e7.ja,MQe:b.step.MH});c()},mZy=function({e7:a,Iid:b,she:c,pa:d,userId:e,Kaa:f,ea:g,ya:h,Dl:k,yt:l,errorService:n,Pa:p,Tp:q,Qu:r,R2b:t,Wgd:v,Jf:w}){const x=new eZy,y=new fZy(a,h),z=new gZy(x,y),B=hZy({e7:a,Iid:b,she:c,zEc:y,AEc:x,R2b:t,ya:h}),C=iZy({e7:a,AEc:x,zEc:y,ya:h,Dl:k,
yt:l,errorService:n,Pa:p,Tp:q,Qu:r,Jf:w,Wgd:v,pa:d,ea:g,userId:e,Kaa:f}),D=jZy({e7:a,Iid:b,she:c,zEc:y,AEc:x,ya:h,userId:e});return{l6:RYy(H=>{const K=H.oa,L=kZy(()=>{y.Eh(x,K)},[K]);return G1(lZy,{...H,oa:L,step:x.step,fnp:B,PVp:C,Xhp:D})}),qDo:z}},FYy=class{static create(a,b,c){const d=c.filter(f=>!f.FYg),e=Array.from(new Set(d.map(f=>f.Md)));e.sort((f,g)=>f-g);return new FYy(a,b,c,c.length,d.length,e)}static empty(){return new FYy("",void 0,[])}constructor(a,b,c,d=0,e=0,f=[]){this.ja=a;this.extension=
b;this.PYs=c;this.HKa=d;this.sWn=e;this.JMs=f}},HYy=class{constructor(a,b){this.Iwl=a;this.QYs=b}};__c.uYy.prototype.ktn=__c.ia(1201,async function(){return(await JYy(this)).sWn>0});var nZy=__webpack_require__(31968),oZy=nZy.Fragment,G1=nZy.jsx,WYy=nZy.jsxs;var pZy=__webpack_require__(845212),qZy=pZy.Fragment,VYy=pZy.memo,kZy=pZy.useCallback,rZy=pZy.useEffect;var sZy=__webpack_require__(186901),tZy=sZy.EW,uZy=sZy.h5,vZy=sZy.mJ,wZy=sZy.sH,F1=sZy.XI;var xZy=__webpack_require__,yZy=xZy(208463),zZy=xZy.n_x(yZy)();var RYy=__webpack_require__(647370).PA;var ZYy={eventType:"next_activity_interacted",Ka(a){return __c.rf({action:a.action,folder_id:a.Ad,activity_id:a.KJ,design_id:a.designId,flyout_step_name:a.MQe,flyout_button_name:a.ymi,teacher_selected_id:a.t_o,has_message:a.TAr})}};var AZy=({RD:a,loading:b,label:c,Hn:d,onClick:e,variant:f})=>{a=G1(a,{onClick:e,ib:c,icon:__c.cu,sq:"end",variant:f,zh:"icon-and-label",loading:b,children:c});return d?G1(d,{children:a}):a};var NYy={k4t:__c.pMs,b9t:__c.qMs,F1t:__c.rMs};var QYy=class{static G(a){N(a,{load:F1,Jp:F1,nNa:F1,gWo:F1,qfj:F1,pF:F1,xB:F1,navigate:F1,rhe:F1})}async load(a){if(a.state.name!=="loading"){a.state={name:"loading"};try{const b=await JYy(this.Ome);uZy(()=>{a.state={name:"complete",C3f:b}})}catch(b){uZy(()=>{a.state={name:"complete",C3f:FYy.empty()}})}}}Jp(a){this.qfj(a);this.rhe(a)}nNa(a){this.qfj(a)}gWo(a){a.isAlive||(a.isAlive=!0,this.pF(a),this.load(a))}qfj(a){a.isAlive&&(a.isAlive=!1,this.xB(a))}pF(a){a.zQ=!0}xB(a){a.zQ=!1}navigate(a,b){a.selectedIndex=
b;a=this.viewport;const {Jwl:c,SLs:d}=this.Ome.RCk();b=c[b];const e=d.get(b.Md);if(e){let f;for(const g of e.page.elements)if(__c.nf(g)&&__c.T8d(g)==="quiz"&&__c.R8d.SJb({type:"dict",value:g.Km}).id===b.eg){f=g;break}f&&(a.selection.Vl(e,f),a.gx(e.page))}}rhe(){}constructor(a,b){this.Ome=a;this.viewport=b;QYy.G(this)}};var PYy=class{static G(a){N(a,{isAlive:wZy.ref,zQ:wZy.ref,state:wZy.ref,selectedIndex:wZy.ref,C3f:tZy})}get C3f(){return this.state.name==="complete"?this.state.C3f:void 0}constructor(a){this.RH=a;this.isAlive=(PYy.G(this),!1);this.zQ=!1;this.state={name:"initial"}}};var BZy=__webpack_require__.p+"images/ca0bf826e58cea81062943ae62dc9354.svg";var UYy=({qa:a,$Xd:b})=>WYy(oZy,{children:[G1(R,{children:G1(__c.xo,{children:G1(R,{padding:"2u",children:G1(Wc,{spacing:"2u",children:G1(a,{})})})})}),G1(b,{})]}),SYy=({state:a,selectedIndex:b,navigator:c})=>a.name==="complete"?G1(CZy,{summary:a.C3f,selected:b,navigator:c}):Array.from({length:4}).map((d,e)=>G1("div",{className:"bxMdGQ",children:G1(__c.oj,{shape:"rectangle",index:e})},e)),CZy=VYy(function({summary:a,selected:b,navigator:c}){return a.JMs.map(d=>WYy(qZy,{children:[G1(R,{children:G1(__c.cv,
{text:__c.J("z9AuDg",[d]),tone:"neutralLow"})}),G1(Wc,{spacing:"2u",children:KYy(a,d).map((e,f)=>G1(DZy,{detail:e,oc:!!b&&b===e.index,navigator:c},`miss-pg-${d}-${f}`))})]},d))}),TYy=VYy(function({navigator:a}){return G1(R,{padding:"2u",children:WYy(Wc,{spacing:"1u",children:[G1(__c.Ar,{variant:"secondary",target:"_blank",href:"#",stretch:!0,onClick:a.Jp,children:M("plX84Q")}),G1(nj,{variant:"primary",onClick:a.nNa,stretch:!0,children:M("wWcg4g")})]})})}),DZy=VYy(function({detail:a,oc:b,navigator:c}){const d=
kZy(()=>c.navigate(a.index),[a,c]);return G1(__c.$t,{onClick:d,variant:"unstyled",role:"menuitem",children:G1(R,{padding:"2u",borderRadius:"element",border:"low",className:zZy("nhGFbQ",{_6tDyHg:b}),children:WYy(__c.tr,{Fa:"start",spacing:"2u",children:[G1(sr,{width:"containedContent",children:G1(__c.gv,{src:BZy,alt:""})}),WYy(sr,{children:[G1(P,{weight:"bold",children:M("+aX2Nw")}),G1(P,{children:a.Elr}),G1(P,{children:__c.J("4jrU8Q",[1])})]})]})})})});var XYy=class{ett(){this.pF();this.L.load(this.store)}constructor(a,b,c){this.store=a;this.L=b;this.pF=c}};var EZy=class{static G(a){N(a,{p0g:wZy.ref,gm:wZy.ref,zyn:wZy.ref,mJk:wZy.ref,xef:tZy,buttonLabel:tZy,iDm:tZy,isLoading:tZy})}get xef(){return!this.mJk&&!!this.zyn?.M3g}get buttonLabel(){return this.xef?__c.cG(this.Za)?M("9UCXOw"):M("PY67EA"):M("Xih7mQ")}get iDm(){return this.xef?M("NPCU0A"):M("w1jAlg")}get isLoading(){return this.p0g||this.gm}constructor(a,b){this.SDd=a;this.Za=b;this.p0g=(EZy.G(this),!0);this.mJk=this.gm=!1}},FZy=class{static G(a){N(a,{V9k:F1,tHi:F1,Obj:F1})}async initialize(a){try{const {M3g:b,
HLj:c,kvl:d}=await this.$$d();uZy(()=>{a.zyn={M3g:b,HLj:c,kvl:d};a.p0g=!1})}catch(b){uZy(()=>a.p0g=!1),this.errorService.ra(Error("Publish - Next Activity: Failed to initialize",{cause:b}))}}async V9k(a,b,c){this.ya.track(ZYy,{action:"next_activity_clicked",Ad:this.r9c,KJ:this.KJ,designId:this.ja});await __c.kMs(this.hvb.lhc,this.hvb.ivb,this.r9c);this.WQi?.();switch(a.SDd){case 0:await this.tHi(a);break;case 1:c?.(b);break;case 2:if(await this.Ome?.ktn()){this.o1r?.ett();break}await this.tHi(a);
break;default:throw new __c.u(a.SDd);}}async tHi(a){if(!a.isLoading){a.gm=!0;try{await $Yy(this),a.xef?this.Obj(a):await bZy(this,4)}catch(b){this.mc.Gb({sb:M("DVi5+w")})}finally{uZy(()=>a.gm=!1)}}}Obj(a){a.mJk=!0;this.Wgd?this.Wgd.eX.postMessage({type:"FINISH_LESSON",rzf:4}):this.tCs()}constructor(a,b,c,d,e,f,g,h,k,l,n,p,q,r,t,v,w){this.r9c=a;this.N1j=b;this.KJ=c;this.ja=d;this.Rnh=e;this.ya=f;this.errorService=g;this.zVc=h;this.Ome=k;this.o1r=l;this.Qb=n;this.hvb=p;this.mc=q;this.Wgd=r;this.tCs=
t;this.$$d=v;this.WQi=w;FZy.G(this)}};var GZy=({title:a,ub:b,onClose:c})=>WYy(__c.tr,{spacing:"0",Fa:"center",children:[b&&G1(sr,{width:"content",children:G1(nj,{variant:"subtleLinkButton",icon:__c.Gr,onClick:b,ariaLabel:M("O7nBVQ")})}),G1(sr,{children:G1(P,{size:"medium",weight:"bold",children:a})}),c&&G1(sr,{width:"content",children:G1(nj,{variant:"subtleLinkButton",icon:__c.Ir,onClick:c,ariaLabel:M("1aujCA")})})]}),HZy=({children:a,...b})=>G1(R,{Fb:"2u",paddingTop:"1u",paddingBottom:"2u",className:b.vf==="fill"?"_4_Dj1g":"_10qgYQ",
children:WYy(Wc,{spacing:"2u",children:[G1(GZy,{...b}),G1(R,{children:a})]})});var IZy=({Q6p:a,vf:b,onClose:c})=>G1(HZy,{title:M("WDTPQg"),vf:b,onClose:c,children:a});var JZy=class{q8b(a){this.ya.track(__c.Hgs,{action:"step_shown",MH:"activity_sent",designId:this.e7.ja,studentId:this.userId,teacherId:a,MZh:"lesson"})}async rhe(a){this.ya.track(ZYy,{action:"flyout_button_clicked",Ad:this.e7.CEc,KJ:this.e7.KJ,designId:this.e7.ja,MQe:"activity_sent",ymi:"next_activity"});await bZy(this.Iid);a()}constructor(a,b,c,d,e){this.e7=a;this.Iid=b;this.she=c;this.ya=d;this.userId=e}};var jZy=({e7:a,Iid:b,she:c,zEc:d,AEc:e,ya:f,userId:g})=>{const h=new JZy(a,b,c,f,g);return RYy(({oa:k,l2:l,NDc:n,vf:p})=>{rZy(()=>{h.q8b(l)},[l]);const q=kZy(async()=>{await h.rhe(k)},[k]),r=kZy(()=>{dZy(d,e,k)},[k]);return G1(IZy,{Q6p:G1(__c.Fgs,{NDc:n,oN:G1(nj,{variant:"primary",loading:c.isLoading,stretch:!0,onClick:q,children:c.buttonLabel})}),vf:p,onClose:r})})};var KZy=__webpack_require__.p+"images/148a6343117d1b138d8988cddbaa8624.svg";var LZy=__webpack_require__.p+"images/0e73aad7e9e645f776d69444529a5ba8.png";var MZy=__webpack_require__.p+"images/b744d512a568d70be79515a277801eae.png";var NZy=(a,b)=>{switch(a.type){case "NEVER_REQUESTED":case "PREVIOUSLY_REQUESTED":return{description:b?M("I8GQ8g"):M("wWXTAw"),Eba:M("dMHw2A"),Aqg:MZy};case "REQUESTED":return{description:b?M("B+DmBQ"):M("BeDX5g"),Eba:M("ys66ng"),Aqg:MZy};case "REJECTED":case "DISMISSED_AFTER_REJECTED":return{description:M("00FnMA"),Eba:M("PyUX/w"),Aqg:LZy};case "APPROVED":case "DISMISSED_AFTER_APPROVED":return{description:b?M("hidmnw"):M("iHEcog"),Eba:M("ys66ng"),Aqg:MZy};default:return{description:b?M("I8GQ8g"):
M("wWXTAw"),Eba:M("dMHw2A"),Aqg:MZy}}},OZy=({j2:a,eVr:b,Z2g:c,vf:d,xef:e,mis:f,RBs:g,Axs:h,onClose:k})=>{const {description:l,Eba:n,Aqg:p}=NZy(a,e);return G1(HZy,{title:M("52t/6g"),vf:d,onClose:k,children:WYy(Wc,{spacing:"3u",children:[G1(R,{display:"flex",justifyContent:"center",alignItems:"center",children:G1(__c.gv,{src:c?KZy:p,alt:"",className:"_lIwfQ"})}),G1(P,{children:c?M("Ve2Nwg"):l}),WYy(Wc,{spacing:"1u",children:[G1(nj,{variant:"primary",disabled:b,stretch:!0,onClick:c?h:g,children:c?f:
n}),!c&&G1(nj,{variant:"secondary",loading:b,stretch:!0,onClick:h,children:f})]})]})})};var PZy=class{async rhe(a){this.ya.track(ZYy,{action:"flyout_button_clicked",Ad:this.e7.CEc,KJ:this.e7.KJ,designId:this.e7.ja,MQe:"check_activity_sent",ymi:"next_activity"});this.e7.rQa.state.type==="NEVER_REQUESTED"?await this.Iid.tHi(this.she):await bZy(this.Iid);a()}constructor(a,b,c,d,e,f,g){this.e7=a;this.Iid=b;this.she=c;this.zEc=d;this.AEc=e;this.R2b=f;this.ya=g}};var hZy=({e7:a,Iid:b,she:c,zEc:d,AEc:e,R2b:f,ya:g})=>{const h=new PZy(a,b,c,d,e,f,g),k=()=>{h.ya.track(ZYy,{action:"flyout_button_clicked",Ad:h.e7.CEc,KJ:h.e7.KJ,designId:h.e7.ja,MQe:"check_activity_sent",ymi:"send_to_teacher"});h.zEc.GAc(h.AEc,{MH:"select_teacher",I:{}})};return RYy(({oa:l,vf:n})=>{const p=kZy(async()=>{await h.rhe(l)},[l]),q=kZy(()=>{dZy(d,e,l)},[l]);return G1(OZy,{j2:a.rQa.state,eVr:c.isLoading,Z2g:a.Z2g,vf:n,xef:c.xef,mis:c.buttonLabel,RBs:k,Axs:p,onClose:q})})};var QZy=class{C5e(a){this.ya.track(ZYy,{action:"teacher_selected",Ad:this.e7.CEc,KJ:this.e7.KJ,designId:this.e7.ja,MQe:"select_teacher",t_o:a})}async onSubmit(a,b){this.e7.rQa.state.type==="APPROVED"&&await this.e7.Dsc.AJm(this.e7.rQa);this.ya.track(ZYy,{action:"flyout_button_clicked",Ad:this.e7.CEc,KJ:this.e7.KJ,designId:this.e7.ja,MQe:"select_teacher",ymi:"send",t_o:a,TAr:!!b})}ub(){this.ya.track(ZYy,{action:"flyout_back_clicked",Ad:this.e7.CEc,KJ:this.e7.KJ,designId:this.e7.ja,MQe:"select_teacher"});
this.zEc.GAc(this.AEc,{MH:"check_activity_sent",I:{}})}constructor(a,b,c,d,e,f,g,h){this.pa=a;this.userId=b;this.ea=c;this.e7=d;this.AEc=e;this.zEc=f;this.ya=g;this.Wgd=h}};var iZy=({e7:a,AEc:b,zEc:c,pa:d,userId:e,Kaa:f,ea:g,ya:h,Dl:k,yt:l,errorService:n,Pa:p,Tp:q,Jf:r,Qu:t,Wgd:v})=>{const w=new QZy(d,e,g,a,b,c,h,v),x=()=>{w.ub()},y=__c.vgs({ya:h,Dl:k,yt:l,errorService:n,Pa:p,Tp:q,Jf:r,Qu:t,pa:d,onSubmit:async(z,B)=>{await w.onSubmit(z,B)},onSubmitSuccess:(z,B)=>{cZy(w,z,B)},C5e:z=>{w.C5e(z)},ea:g,userId:e,Kaa:f,wCe:"lesson"});return RYy(({oa:z,vf:B})=>{const C=kZy(()=>{dZy(c,b,z)},[z]);return G1(HZy,{title:M("eLVGUw"),vf:B,ub:x,onClose:C,children:G1(y,{j2:a.rQa.state})})})};var lZy=({step:a,fnp:b,PVp:c,Xhp:d,...e})=>{switch(a.MH){case "check_activity_sent":return G1(b,{...e,...a.I});case "select_teacher":return G1(c,{...e,...a.I});case "activity_sent":return G1(d,{...e,...a.I});default:throw new __c.u(a);}};var eZy=class{static G(a){N(a,{step:wZy.ref})}constructor(){this.step=(eZy.G(this),{MH:"check_activity_sent",I:{}})}},fZy=class{static G(a){N(a,{reset:F1,GAc:F1})}Eh(a,b){this.reset(a);b()}reset(a){a.step={MH:"check_activity_sent",I:{}}}GAc(a,b){a.step=b}constructor(a,b){this.e7=a;this.ya=b;fZy.G(this)}};var gZy=class{constructor(a,b){this.AEc=a;this.zEc=b;this.hHs=()=>{this.zEc.GAc(this.AEc,{MH:"select_teacher",I:{}})}}};__c.fVy={zBn:function({ge:a,Nz:b,ZYn:c,Za:d,pa:e,userId:f,Kaa:g,ea:h,viewport:k,Nc:l,ya:n,Dl:p,yt:q,fe:r,errorService:t,zVc:v,R2b:w,Pa:x,Tp:y,Qb:z,Ec:B,mc:C,Jf:D,Ea:H,Qu:K,Eb:L,Cq:O,pfd:Q,MPc:T,Pwa:U}){t=t.Xf("lesson_next_activity");n.track(ZYy,{action:"next_activity_shown",KJ:c.KJ,Ad:c.CEc,designId:c.ja});const X=OYy({errorService:t}),aa=__webpack_require__.me(156223).then(()=>__c.RZy),ba=new EZy(c.SDd,d);r=new __c.CYy(f,e,v,q,r);const ea=Promise.resolve(w);L=__c.nMs({userId:f,pa:e,Qu:K,Eb:L,U6g:ea,
pfd:Q,Cq:O,Pwa:U});let fa;c.SDd===2&&(fa=c.Ome);let ka;if(T&&fa&&k&&l){const {sLp:Aa,controller:wa}=YYy({Ome:fa,viewport:k});ka=wa;vZy(()=>wa.store.zQ,xa=>{l.Ly=xa?Aa:void 0})}const ma=new FZy(c.CEc,c.fIk?2:void 0,c.KJ,c.ja,r,n,t,v,fa,ka,z,L,C,X,async()=>{var {bRm:Aa}=await aa;Aa=Aa({Ad:c.CEc,Za:d,V:n,Ec:B,T6c:c.T6c});H(Aa)},c.$$d,b.Uof?.Ng);k=RYy(({onClick:Aa,...wa})=>{const xa=kZy(async za=>{await ma.V9k(ba,za,Aa)},[Aa]);rZy(()=>{ma.initialize(ba)},[]);return G1(AZy,{...wa,loading:ba.isLoading,
label:ba.iDm,Hn:void 0,onClick:xa,variant:"primary"})});v=RYy(({onClick:Aa,...wa})=>{const xa=kZy(async za=>{await ma.V9k(ba,za,Aa)},[Aa]);rZy(()=>{ma.initialize(ba)},[]);return G1(AZy,{...wa,loading:ba.isLoading,label:ba.buttonLabel,Hn:b.Uof?.Component,onClick:xa,variant:"primary"})});const {l6:na,qDo:qa}=c.SDd===1?mZy({e7:c,she:ba,Iid:ma,pa:e,userId:f,ea:h,ya:n,Dl:p,yt:q,errorService:t,Pa:x,Tp:y,Qu:K,R2b:w,Jf:D,Wgd:X,Kaa:g}):{l6:void 0,qDo:void 0},oa={Button:v,qa:na},pa={Button:k,qa:na};a.kc(({header:Aa})=>
{Aa.KRh=oa;Aa.LRh=pa});qa&&c.SDd===1&&["REJECTED","DISMISSED_AFTER_REJECTED"].includes(c.rQa.state.type)&&(qa.hHs(),a.zmb(oa),a.zmb(pa))}};
}).call(self, self._456c437108d2d2713799e19380be528d);}

}])
;// __FILE_CONTENT_FOR__:07b3a43702afbe10.js
(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[1981],{

/***/ 225524:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);self._456c437108d2d2713799e19380be528d = self._456c437108d2d2713799e19380be528d || {};(function(__c) {
}).call(self, self._456c437108d2d2713799e19380be528d);}

}])
;// __FILE_CONTENT_FOR__:c2c2a10e1a9d7ac5.js
(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[56052],{

/***/ 798052:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(154652);__web_req__(794024);self._456c437108d2d2713799e19380be528d = self._456c437108d2d2713799e19380be528d || {};(function(__c) {var S=__c.S;__c.Uys=__c.G(()=>({type:__c.A("A?",1,"BY_RESOURCES"),pa:S(31),resources:__c.Ua(32,__c.bJ)}));__c.Vys=__c.G(()=>({jlc:__c.Wa(1,__c.tkc),pa:S(2),zPd:S(3),q1s:S(5),userId:S(4)}));__c.Wys=__c.G(()=>({type:__c.A("A?",1,"BY_REMIXED_DOCUMENT_ID"),pa:S(51),Bro:__c.E(52,__c.ZQo),AQc:__c.F(53,__c.vkc)}));
}).call(self, self._456c437108d2d2713799e19380be528d);}

}])
;// __FILE_CONTENT_FOR__:0fa9ba1a19badda4.js
(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[48888],{

/***/ 658579:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(154652);self._456c437108d2d2713799e19380be528d = self._456c437108d2d2713799e19380be528d || {};(function(__c) {var S=__c.S;var FZo=()=>({pa:S(21),resource:__c.E(22,__c.bJ)});var GZo=__c.G(()=>({...FZo(),type:__c.A("A?",1,"GOOGLE_CLASSROOM_LINK"),courseId:S(41),courseWorkId:S(42),alternateLink:S(43)}));var HZo=__c.G(()=>({...FZo(),type:__c.A("A?",2,"CANVAS_LINK"),courseId:S(43),I1r:__c.V(44),Eov:__c.V(45)}));__c.IZo=__c.ab(()=>({type:[1,GZo,2,HZo]}),FZo);
}).call(self, self._456c437108d2d2713799e19380be528d);}

}])
;// __FILE_CONTENT_FOR__:50c1934786d8c85f.js
(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[72680],{

/***/ 608095:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(658579);__web_req__(154652);self._456c437108d2d2713799e19380be528d = self._456c437108d2d2713799e19380be528d || {};(function(__c) {__c.JZo=__c.G(()=>({Bpa:__c.E(3,__c.IZo)}));__c.KZo=__c.I(()=>[1,2]);__c.LZo=__c.G(()=>({pa:__c.S(1),resource:__c.E(2,__c.bJ),fta:__c.S(3),mV:__c.Wa(4,__c.KZo)}));
}).call(self, self._456c437108d2d2713799e19380be528d);}

}])
;// __FILE_CONTENT_FOR__:41bdc933b2bb2315.js
(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[3243],{

/***/ 532265:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);self._456c437108d2d2713799e19380be528d = self._456c437108d2d2713799e19380be528d || {};(function(__c) {__c.RXn=__c.I(()=>[0,1]);
}).call(self, self._456c437108d2d2713799e19380be528d);}

}])
;// __FILE_CONTENT_FOR__:adac7d1a2d56a3a9.js
(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[83840],{

/***/ 77675:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(154652);__web_req__(862751);__web_req__(532265);self._456c437108d2d2713799e19380be528d = self._456c437108d2d2713799e19380be528d || {};(function(__c) {__c.kjo=__c.G(()=>({pa:__c.S(1),resource:__c.E(2,__c.bJ),fta:__c.S(3),TOj:__c.Ua(4,__c.Tqk),message:__c.V(5),Cdt:__c.W(6,!0)}));__c.ljo=__c.G(()=>({ja:__c.S(1),Hqc:__c.Wa(2,__c.RXn)}));
}).call(self, self._456c437108d2d2713799e19380be528d);}

}])
;// __FILE_CONTENT_FOR__:14c8a0be568173c2.js
(self["webpackChunk_canva_web"] = self["webpackChunk_canva_web"] || []).push([[30099],{

/***/ 133686:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(77675);__web_req__(361075);__web_req__(154652);__web_req__(608095);__web_req__(798052);__web_req__(140332);__web_req__(16980);__web_req__(225524);__web_req__(321092);__web_req__(794024);__web_req__(658579);self._456c437108d2d2713799e19380be528d = self._456c437108d2d2713799e19380be528d || {};(function(__c) {var nh=__c.nh;var qh=__c.qh;var S=__c.S;var G=__c.G;var ab=__c.ab;var pFA=ab(()=>({type:[1,__c.Wqk]}),__c.Vqk);var qFA=ab(()=>({type:[1,__c.Uys]}),()=>({}));var rFA=G(()=>({pa:S(1),ja:S(2)}));var sFA=()=>({limit:__c.vp(11,20),continuation:__c.V(12)});var tFA=G(()=>({...sFA(),type:__c.A("A?",1,"BY_COURSE_ID"),pa:S(31),courseId:S(32)}));var uFA=ab(()=>({type:[1,tFA]}),sFA);var vFA=ab(()=>({type:[1,__c.Wys]}),()=>({}));var wFA=G(()=>({...__c.V1r(),type:__c.A("A?",2,"BY_TOKEN"),hCv:S(31)}));var xFA=ab(()=>({type:[1,__c.W1r,2,wFA]}),__c.V1r);var yFA=G(()=>({pa:S(1),resource:__c.E(2,__c.bJ),fta:S(3),mV:__c.Wa(4,__c.KZo),nxb:__c.W(5)}));var zFA=G(()=>({type:__c.A("A?",1,"BY_RESOURCE_AND_ASSIGNER"),pa:S(1),resource:__c.E(2,__c.bJ),Sf:__c.V(5),fta:S(3),mV:__c.Wa(4,__c.KZo)}));var AFA=ab(()=>({type:[1,zFA]}),()=>({}));var BFA,C4;
BFA=class{async dQm(a){const b=qh(nh([C4,"assignments","bulk-create"])),[c,{ypp:d}]=await Promise.all([this.Da.post(b,__c.kjo.serialize(a),{Qa:"createassignments"}),__webpack_require__.me(713871).then(()=>({ypp:__c.SFt}))]);return d.deserialize(c)}async Yvc(a){const b=qh(nh([C4,"assignments","find"])),[c,{Fyp:d}]=await Promise.all([this.Da.post(b,pFA.serialize(a),{Qa:"findassignments"}),__webpack_require__.me(713871).then(()=>({Fyp:__c.WFt}))]);return d.deserialize(c)}async g$j(a){const b=qh(nh([C4,
"assignments","delete"])),[c,{jtp:d}]=await Promise.all([this.Da.post(b,__c.Uqk.serialize(a),{Qa:"deleteassignment"}),__webpack_require__.me(713871).then(()=>({jtp:__c.TFt}))]);return d.deserialize(c)}async Dwf(a){const b=nh([C4,"assigned"]);__c.lh(b,{brandId:__c.m(a.pa),"resource.id":__c.m(a.resource.id),"resource.type":__c.Rqk.serialize(a.resource.type),assignedUser:__c.m(a.IZh)});a=qh(b);const [c,{gnp:d}]=await Promise.all([this.Da.get(a,{Qa:"checkassigned"}),__webpack_require__.me(713871).then(()=>
({gnp:__c.dFA}))]);return d.deserialize(c)}async JRm(a){const b=qh(nh([C4,"assignments","resource-external-context","create"])),[c,{jrp:d}]=await Promise.all([this.Da.post(b,__c.JZo.serialize(a),{Qa:"createresourceexternalcontext"}),__webpack_require__.me(713871).then(()=>({jrp:__c.eFA}))]);return d.deserialize(c)}async DHf(a){const b=qh(nh([C4,"assignments","resource-external-context","find"])),[c,{AAp:d}]=await Promise.all([this.Da.post(b,qFA.serialize(a),{Qa:"findresourceexternalcontext"}),__webpack_require__.me(713871).then(()=>
({AAp:__c.bGt}))]);return d.deserialize(c)}async Zfj(a){const b=qh(nh([C4,"assignments","resource-external-context","submit"])),[c,{WXp:d}]=await Promise.all([this.Da.post(b,__c.Vys.serialize(a),{Qa:"submitresourceexternalcontext"}),__webpack_require__.me(713871).then(()=>({WXp:__c.fFA}))]);return d.deserialize(c)}async AWl(a){const b=qh(nh([C4,"assignments","solo-work","start"])),[c,{AXp:d}]=await Promise.all([this.Da.post(b,__c.BUm.serialize(a),{Qa:"startsoloworkassignment"}),__webpack_require__.me(713871).then(()=>
({AXp:__c.gFA}))]);return d.deserialize(c)}async Coa(a){const b=qh(nh([C4,"document-summaries","get"])),[c,{hxj:d}]=await Promise.all([this.Da.post(b,rFA.serialize(a),{Qa:"getdocumentsummary"}),__webpack_require__.me(713871).then(()=>({hxj:__c.cGt}))]);return d.deserialize(c)}async Zvc(a){const b=qh(nh([C4,"document-summaries","find"])),[c,{Ewj:d}]=await Promise.all([this.Da.post(b,uFA.serialize(a),{Qa:"finddocumentsummaries"}),__webpack_require__.me(713871).then(()=>({Ewj:__c.aGt}))]);return d.deserialize(c)}async I9l(a){const b=
qh(nh([C4,"user-document-progress","update"])),[c,{x1p:d}]=await Promise.all([this.Da.post(b,vFA.serialize(a),{Qa:"updateuserdocumentprogress"}),__webpack_require__.me(713871).then(()=>({x1p:__c.oFA}))]);return d.deserialize(c)}async SPg(a){const b=qh(nh([C4,"resource-assigners","find"])),[c,{zAp:d}]=await Promise.all([this.Da.post(b,xFA.serialize(a),{Qa:"findresourceassigners"}),__webpack_require__.me(713871).then(()=>({zAp:__c.iFA}))]);return d.deserialize(c)}async Eyf(a){const b=qh(nh([C4,"token",
"create"])),[c,{xpp:d}]=await Promise.all([this.Da.post(b,yFA.serialize(a),{Qa:"createassignmenttoken"}),__webpack_require__.me(713871).then(()=>({xpp:__c.lFA}))]);return d.deserialize(c)}async Ili(a){const b=qh(nh([C4,"token","find"])),[c,{Eyp:d}]=await Promise.all([this.Da.post(b,AFA.serialize(a),{Qa:"findassignmenttoken"}),__webpack_require__.me(713871).then(()=>({Eyp:__c.mFA}))]);return d.deserialize(c)}async h$j(a){const b=qh(nh([C4,"token","delete"])),[c,{ktp:d}]=await Promise.all([this.Da.post(b,
__c.LZo.serialize(a),{Qa:"deleteassignmenttoken"}),__webpack_require__.me(713871).then(()=>({ktp:__c.nFA}))]);return d.deserialize(c)}async Jnj(a){const b=qh(nh([C4,"activity-experiences"])),[c,{P1p:d}]=await Promise.all([this.Da.post(b,__c.ljo.serialize(a),{Qa:"upsertactivityexperience"}),__webpack_require__.me(713871).then(()=>({P1p:__c.dGt}))]);return d.deserialize(c)}async Vrk(a){const b=qh(nh([C4,"activity-experiences","find"])),[c,{uyp:d}]=await Promise.all([this.Da.post(b,__c.Vyr.serialize(a),
{Qa:"findactivityexperiences"}),__webpack_require__.me(713871).then(()=>({uyp:__c.UFt}))]);return d.deserialize(c)}constructor(a){this.Da=a}};C4="assignment";__c.oPa={};__c.oPa.qIp=BFA;
}).call(self, self._456c437108d2d2713799e19380be528d);}

}])
//# sourceMappingURL=https://chunk-composing.canva.com/chunk-batch-sm/9_sourcemaps/4a930e2397c76056.js.map+8_sourcemaps/6a864be9ddd5733e.js.map+29_sourcemaps/204532102349e2a1.js.map+32_sourcemaps/8c0de5e7160b8856.js.map+8+8_sourcemaps/c2c2a10e1a9d7ac5.js.map+8_sourcemaps/0fa9ba1a19badda4.js.map+8_sourcemaps/50c1934786d8c85f.js.map+8_sourcemaps/41bdc933b2bb2315.js.map+8_sourcemaps/adac7d1a2d56a3a9.js.map+17_sourcemaps/14c8a0be568173c2.js.map